-- CREATE DATABASE focuscam CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE focuscam;

-- CREATE TABLE USERS (
--     id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     image LONGBLOB NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    image_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
